server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 缓存静态资源
    location ~* \.(js|css|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}