extends Node
## 关卡数据单例（与浏览器版 LEVELS 对齐，共 8 关）
## 每关: { name, start_sun, waves: [ { zombies: [ {type, delay} ] } ] }
## 注意: 浏览器版 delay 单位为 ms，此处已转换为秒（除以 1000）

var levels: Dictionary = {
	# 第 1 关
	1: {
		"name": "第一关：初战",
		"start_sun": 150,
		"waves": [
			# 第1波: 3个普通僵尸
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "normal", "delay": 4.0 },
				{ "type": "normal", "delay": 8.0 },
			],
			# 第2波: 4个普通僵尸 + 1个路障
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "normal", "delay": 3.0 },
				{ "type": "cone", "delay": 6.0 },
				{ "type": "normal", "delay": 9.0 },
				{ "type": "normal", "delay": 12.0 },
			],
			# 第3波: 2个奔跑僵尸 + 3个普通
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "normal", "delay": 3.0 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "normal", "delay": 9.0 },
				{ "type": "normal", "delay": 12.0 },
			],
			# 第4波: 混合大军
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "cone", "delay": 3.0 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "normal", "delay": 9.0 },
				{ "type": "cone", "delay": 12.0 },
				{ "type": "runner", "delay": 15.0 },
			],
			# 第5波: 最终波
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "cone", "delay": 2.5 },
				{ "type": "runner", "delay": 5.0 },
				{ "type": "normal", "delay": 7.5 },
				{ "type": "cone", "delay": 10.0 },
				{ "type": "runner", "delay": 12.5 },
				{ "type": "normal", "delay": 15.0 },
				{ "type": "cone", "delay": 17.5 },
			],
		],
	},
	# 第 2 关
	2: {
		"name": "第二关：集结",
		"start_sun": 175,
		"waves": [
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "normal", "delay": 2.5 },
				{ "type": "normal", "delay": 5.0 },
				{ "type": "cone", "delay": 7.5 },
				{ "type": "normal", "delay": 10.0 },
				{ "type": "cone", "delay": 12.5 },
				{ "type": "runner", "delay": 15.0 },
			],
			[
				{ "type": "normal", "delay": 0.0 },
				{ "type": "cone", "delay": 2.0 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "normal", "delay": 6.0 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "runner", "delay": 10.0 },
				{ "type": "normal", "delay": 12.0 },
				{ "type": "runner", "delay": 14.0 },
				{ "type": "cone", "delay": 16.0 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 2.0 },
				{ "type": "normal", "delay": 4.0 },
				{ "type": "cone", "delay": 6.0 },
				{ "type": "runner", "delay": 8.0 },
				{ "type": "normal", "delay": 10.0 },
				{ "type": "cone", "delay": 12.0 },
				{ "type": "runner", "delay": 14.0 },
				{ "type": "normal", "delay": 16.0 },
				{ "type": "cone", "delay": 18.0 },
			],
		],
	},
	# 第 3 关
	3: {
		"name": "第三关：疾驰",
		"start_sun": 200,
		"waves": [
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 1.5 },
				{ "type": "normal", "delay": 3.0 },
				{ "type": "runner", "delay": 4.5 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "cone", "delay": 7.5 },
				{ "type": "runner", "delay": 9.0 },
				{ "type": "normal", "delay": 10.5 },
				{ "type": "runner", "delay": 12.0 },
			],
			[
				{ "type": "cone", "delay": 0.0 },
				{ "type": "runner", "delay": 1.5 },
				{ "type": "cone", "delay": 3.0 },
				{ "type": "runner", "delay": 4.5 },
				{ "type": "normal", "delay": 6.0 },
				{ "type": "runner", "delay": 7.5 },
				{ "type": "cone", "delay": 9.0 },
				{ "type": "runner", "delay": 10.5 },
				{ "type": "runner", "delay": 12.0 },
				{ "type": "cone", "delay": 13.5 },
				{ "type": "normal", "delay": 15.0 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 1.0 },
				{ "type": "runner", "delay": 2.0 },
				{ "type": "cone", "delay": 3.0 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "runner", "delay": 5.0 },
				{ "type": "normal", "delay": 6.0 },
				{ "type": "runner", "delay": 7.0 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "runner", "delay": 9.0 },
				{ "type": "runner", "delay": 10.0 },
				{ "type": "normal", "delay": 11.0 },
				{ "type": "runner", "delay": 12.0 },
				{ "type": "cone", "delay": 13.0 },
			],
		],
	},
	# 第 4 关
	4: {
		"name": "第四关：铁桶",
		"start_sun": 225,
		"waves": [
			[
				{ "type": "cone", "delay": 0.0 },
				{ "type": "cone", "delay": 2.0 },
				{ "type": "normal", "delay": 4.0 },
				{ "type": "cone", "delay": 6.0 },
				{ "type": "normal", "delay": 8.0 },
				{ "type": "cone", "delay": 10.0 },
				{ "type": "runner", "delay": 12.0 },
				{ "type": "cone", "delay": 14.0 },
				{ "type": "normal", "delay": 16.0 },
			],
			[
				{ "type": "cone", "delay": 0.0 },
				{ "type": "runner", "delay": 1.5 },
				{ "type": "cone", "delay": 3.0 },
				{ "type": "cone", "delay": 4.5 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "normal", "delay": 7.5 },
				{ "type": "cone", "delay": 9.0 },
				{ "type": "runner", "delay": 10.5 },
				{ "type": "cone", "delay": 12.0 },
				{ "type": "runner", "delay": 13.5 },
				{ "type": "normal", "delay": 15.0 },
				{ "type": "cone", "delay": 16.5 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "cone", "delay": 1.0 },
				{ "type": "runner", "delay": 2.0 },
				{ "type": "cone", "delay": 3.0 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "cone", "delay": 5.0 },
				{ "type": "normal", "delay": 6.0 },
				{ "type": "runner", "delay": 7.0 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "runner", "delay": 9.0 },
				{ "type": "cone", "delay": 10.0 },
				{ "type": "runner", "delay": 11.0 },
				{ "type": "normal", "delay": 12.0 },
				{ "type": "cone", "delay": 13.0 },
				{ "type": "runner", "delay": 14.0 },
				{ "type": "cone", "delay": 15.0 },
			],
		],
	},
	# 第 5 关
	5: {
		"name": "第五关：狂潮",
		"start_sun": 250,
		"waves": [
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 0.8 },
				{ "type": "cone", "delay": 1.6 },
				{ "type": "runner", "delay": 2.4 },
				{ "type": "normal", "delay": 3.2 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "cone", "delay": 4.8 },
				{ "type": "runner", "delay": 5.6 },
				{ "type": "normal", "delay": 6.4 },
				{ "type": "cone", "delay": 7.2 },
				{ "type": "runner", "delay": 8.0 },
				{ "type": "runner", "delay": 8.8 },
				{ "type": "normal", "delay": 9.6 },
				{ "type": "cone", "delay": 10.4 },
			],
			[
				{ "type": "cone", "delay": 0.0 },
				{ "type": "runner", "delay": 0.7 },
				{ "type": "cone", "delay": 1.4 },
				{ "type": "runner", "delay": 2.1 },
				{ "type": "normal", "delay": 2.8 },
				{ "type": "runner", "delay": 3.5 },
				{ "type": "cone", "delay": 4.2 },
				{ "type": "runner", "delay": 4.9 },
				{ "type": "cone", "delay": 5.6 },
				{ "type": "normal", "delay": 6.3 },
				{ "type": "runner", "delay": 7.0 },
				{ "type": "cone", "delay": 7.7 },
				{ "type": "runner", "delay": 8.4 },
				{ "type": "runner", "delay": 9.1 },
				{ "type": "cone", "delay": 9.8 },
				{ "type": "normal", "delay": 10.5 },
				{ "type": "runner", "delay": 11.2 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 0.5 },
				{ "type": "cone", "delay": 1.0 },
				{ "type": "runner", "delay": 1.5 },
				{ "type": "runner", "delay": 2.0 },
				{ "type": "cone", "delay": 2.5 },
				{ "type": "normal", "delay": 3.0 },
				{ "type": "runner", "delay": 3.5 },
				{ "type": "cone", "delay": 4.0 },
				{ "type": "runner", "delay": 4.5 },
				{ "type": "runner", "delay": 5.0 },
				{ "type": "cone", "delay": 5.5 },
				{ "type": "normal", "delay": 6.0 },
				{ "type": "runner", "delay": 6.5 },
				{ "type": "cone", "delay": 7.0 },
				{ "type": "runner", "delay": 7.5 },
				{ "type": "runner", "delay": 8.0 },
				{ "type": "cone", "delay": 8.5 },
				{ "type": "normal", "delay": 9.0 },
				{ "type": "runner", "delay": 9.5 },
			],
		],
	},
	# 第 6 关
	6: {
		"name": "第六关：最终防线",
		"start_sun": 275,
		"waves": [
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "cone", "delay": 0.6 },
				{ "type": "runner", "delay": 1.2 },
				{ "type": "runner", "delay": 1.8 },
				{ "type": "cone", "delay": 2.4 },
				{ "type": "normal", "delay": 3.0 },
				{ "type": "runner", "delay": 3.6 },
				{ "type": "cone", "delay": 4.2 },
				{ "type": "runner", "delay": 4.8 },
				{ "type": "normal", "delay": 5.4 },
				{ "type": "cone", "delay": 6.0 },
				{ "type": "runner", "delay": 6.6 },
				{ "type": "runner", "delay": 7.2 },
				{ "type": "cone", "delay": 7.8 },
				{ "type": "normal", "delay": 8.4 },
				{ "type": "runner", "delay": 9.0 },
				{ "type": "cone", "delay": 9.6 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 0.4 },
				{ "type": "cone", "delay": 0.8 },
				{ "type": "runner", "delay": 1.2 },
				{ "type": "runner", "delay": 1.6 },
				{ "type": "cone", "delay": 2.0 },
				{ "type": "normal", "delay": 2.4 },
				{ "type": "runner", "delay": 2.8 },
				{ "type": "cone", "delay": 3.2 },
				{ "type": "runner", "delay": 3.6 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "cone", "delay": 4.4 },
				{ "type": "normal", "delay": 4.8 },
				{ "type": "runner", "delay": 5.2 },
				{ "type": "cone", "delay": 5.6 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "runner", "delay": 6.4 },
				{ "type": "cone", "delay": 6.8 },
				{ "type": "normal", "delay": 7.2 },
				{ "type": "runner", "delay": 7.6 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "runner", "delay": 8.4 },
			],
			[
				{ "type": "runner", "delay": 0.0 },
				{ "type": "runner", "delay": 0.3 },
				{ "type": "cone", "delay": 0.6 },
				{ "type": "runner", "delay": 0.9 },
				{ "type": "runner", "delay": 1.2 },
				{ "type": "cone", "delay": 1.5 },
				{ "type": "runner", "delay": 1.8 },
				{ "type": "normal", "delay": 2.1 },
				{ "type": "runner", "delay": 2.4 },
				{ "type": "cone", "delay": 2.7 },
				{ "type": "runner", "delay": 3.0 },
				{ "type": "runner", "delay": 3.3 },
				{ "type": "cone", "delay": 3.6 },
				{ "type": "normal", "delay": 3.9 },
				{ "type": "runner", "delay": 4.2 },
				{ "type": "cone", "delay": 4.5 },
				{ "type": "runner", "delay": 4.8 },
				{ "type": "runner", "delay": 5.1 },
				{ "type": "cone", "delay": 5.4 },
				{ "type": "normal", "delay": 5.7 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "cone", "delay": 6.3 },
				{ "type": "runner", "delay": 6.6 },
				{ "type": "runner", "delay": 6.9 },
				{ "type": "cone", "delay": 7.2 },
				{ "type": "normal", "delay": 7.5 },
				{ "type": "runner", "delay": 7.8 },
				{ "type": "cone", "delay": 8.1 },
				{ "type": "runner", "delay": 8.4 },
			],
		],
	},
	# 第 7 关
	7: {
		"name": "第七关：铁桶来袭",
		"start_sun": 300,
		"waves": [
			[
				{ "type": "bucket", "delay": 0.0 },
				{ "type": "normal", "delay": 2.0 },
				{ "type": "bucket", "delay": 4.0 },
				{ "type": "newspaper", "delay": 6.0 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "bucket", "delay": 10.0 },
				{ "type": "runner", "delay": 12.0 },
			],
			[
				{ "type": "pole_vault", "delay": 0.0 },
				{ "type": "bucket", "delay": 2.0 },
				{ "type": "newspaper", "delay": 4.0 },
				{ "type": "pole_vault", "delay": 6.0 },
				{ "type": "bucket", "delay": 8.0 },
				{ "type": "runner", "delay": 10.0 },
				{ "type": "pole_vault", "delay": 12.0 },
				{ "type": "newspaper", "delay": 14.0 },
			],
			[
				{ "type": "bucket", "delay": 0.0 },
				{ "type": "pole_vault", "delay": 1.0 },
				{ "type": "newspaper", "delay": 2.0 },
				{ "type": "bucket", "delay": 3.0 },
				{ "type": "runner", "delay": 4.0 },
				{ "type": "pole_vault", "delay": 5.0 },
				{ "type": "bucket", "delay": 6.0 },
				{ "type": "newspaper", "delay": 7.0 },
				{ "type": "cone", "delay": 8.0 },
				{ "type": "pole_vault", "delay": 9.0 },
				{ "type": "runner", "delay": 10.0 },
			],
		],
	},
	# 第 8 关
	8: {
		"name": "第八关：最终铁桶防线",
		"start_sun": 325,
		"waves": [
			[
				{ "type": "bucket", "delay": 0.0 },
				{ "type": "pole_vault", "delay": 1.0 },
				{ "type": "bucket", "delay": 2.0 },
				{ "type": "newspaper", "delay": 3.0 },
				{ "type": "bucket", "delay": 4.0 },
				{ "type": "runner", "delay": 5.0 },
				{ "type": "pole_vault", "delay": 6.0 },
				{ "type": "bucket", "delay": 7.0 },
				{ "type": "newspaper", "delay": 8.0 },
			],
			[
				{ "type": "bucket", "delay": 0.0 },
				{ "type": "pole_vault", "delay": 0.8 },
				{ "type": "bucket", "delay": 1.6 },
				{ "type": "runner", "delay": 2.4 },
				{ "type": "pole_vault", "delay": 3.2 },
				{ "type": "newspaper", "delay": 4.0 },
				{ "type": "bucket", "delay": 4.8 },
				{ "type": "pole_vault", "delay": 5.6 },
				{ "type": "newspaper", "delay": 6.4 },
				{ "type": "bucket", "delay": 7.2 },
				{ "type": "runner", "delay": 8.0 },
				{ "type": "cone", "delay": 8.8 },
			],
			[
				{ "type": "bucket", "delay": 0.0 },
				{ "type": "pole_vault", "delay": 0.6 },
				{ "type": "bucket", "delay": 1.2 },
				{ "type": "newspaper", "delay": 1.8 },
				{ "type": "pole_vault", "delay": 2.4 },
				{ "type": "runner", "delay": 3.0 },
				{ "type": "bucket", "delay": 3.6 },
				{ "type": "pole_vault", "delay": 4.2 },
				{ "type": "newspaper", "delay": 4.8 },
				{ "type": "bucket", "delay": 5.4 },
				{ "type": "runner", "delay": 6.0 },
				{ "type": "pole_vault", "delay": 6.6 },
				{ "type": "cone", "delay": 7.2 },
				{ "type": "newspaper", "delay": 7.8 },
			],
		],
	},
        # 第 9 关（夜间：天空不掉阳光，开局 150 阳光）
        9: {
                "name": "第九关：夜幕降临",
                "start_sun": 150,
                "night": true,
                "waves": [
                        # 第 1 波: 铁桶 + 撑杆 + 读报混合
                        [
                                { "type": "bucket", "delay": 0.0 },
                                { "type": "pole_vault", "delay": 1.5 },
                                { "type": "newspaper", "delay": 3.0 },
                                { "type": "bucket", "delay": 4.5 },
                                { "type": "runner", "delay": 6.0 },
                                { "type": "pole_vault", "delay": 7.5 },
                                { "type": "newspaper", "delay": 9.0 },
                        ],
                        # 第 2 波: 铁桶 + 撑杆 + 读报 + 路障
                        [
                                { "type": "bucket", "delay": 0.0 },
                                { "type": "pole_vault", "delay": 1.0 },
                                { "type": "newspaper", "delay": 2.0 },
                                { "type": "bucket", "delay": 3.0 },
                                { "type": "runner", "delay": 4.0 },
                                { "type": "pole_vault", "delay": 5.0 },
                                { "type": "newspaper", "delay": 6.0 },
                                { "type": "cone", "delay": 7.0 },
                                { "type": "bucket", "delay": 8.0 },
                                { "type": "pole_vault", "delay": 9.0 },
                                { "type": "newspaper", "delay": 10.0 },
                        ],
                        # 第 3 波: 最终波，混合大军
                        [
                                { "type": "bucket", "delay": 0.0 },
                                { "type": "pole_vault", "delay": 0.7 },
                                { "type": "newspaper", "delay": 1.4 },
                                { "type": "bucket", "delay": 2.1 },
                                { "type": "runner", "delay": 2.8 },
                                { "type": "pole_vault", "delay": 3.5 },
                                { "type": "newspaper", "delay": 4.2 },
                                { "type": "bucket", "delay": 4.9 },
                                { "type": "runner", "delay": 5.6 },
                                { "type": "pole_vault", "delay": 6.3 },
                                { "type": "cone", "delay": 7.0 },
                                { "type": "newspaper", "delay": 7.7 },
                                { "type": "bucket", "delay": 8.4 },
                                { "type": "pole_vault", "delay": 9.1 },
                        ],
                ],
        },

## 所有关卡 ID（升序）
func all_ids() -> Array:
	return levels.keys()
